export const posts = [
  {
    id: 1,
    title: 'Suvine töökorraldus',
    content:
      '<b>TÖÖKORRALDUS</b><br><br><b>05.06-22.06</b><br>AVATUD ÜHISRÜHMAD TALLINNA TN 49, KASTANI TN 6<br><br><b>ALATES 26.06-21.07</b> PAIDE LASTEAED KOLLEKTIIVPUHKUSEL, AVATUD ÜHISRÜHMAD SOOKURE LASTEAIAS (SOO 16)<br><br><br><br><b>24.07-18.08</b><br>AVATUD PAIDE LINNA ÜLESED ÜHISRÜHMAD TALLINNA TN 49.<br><br><br><b>21.08</b><br>TAASTUB TAVAPÄRANE TÖÖKORRALDUS<br><br><br><span style="color: green;">RÜHMADE JAOTUS</span><br><b>05.06-22.06</b><br><br><u>TALLINNA TN 49</u><br>VÕILILL+ SAIALILL- VÕILILLE RÜHMARUUM<br><br>SINILILL+PÄEVALILL- LASTE VASTUVÕTT OMA RÜHMARUUMIS (SINILILL, PÄEVALILL)<br><br>RUKKILILL+KAERALILL+MEELESPEA- KAERALILLE RÜHMARUUM<br><br><br><u>KASTANI TN 6</u><br>VIHMAPAI+TUULEPAI- VIHMAPAI RÜHMARUUM<br><br>VIKERKAAREPAI+TÄHEPAI- VIKERKAAREPAI RÜHMARUUM<br><br>PÄIKESEPAI+PILVEPAI- PÄIKESEPAI RÜHMARUUM<br><br><br><span style="color: green;">ALATES <b>24.07</b> (ÜHISRÜHMAD TALLINNA TN 49)</span><br><b>24.07- 28.07</b><br><br>I- Saialill, Võilill, Tuulepai, Vihmapai- Võilille rühmaruum<br><br>II- Tähepai, Sinilill, Mõmmikud, Krõllid, Mesimummid, Lepatriinud- Sinilille rühmaruum<br><br>III- Sookurekesed, Naerupallid, Päevalill, Päikesepai- Päevalille rühmaruum<br><br>IV- Kiilikesed, Vikerkaarepai, Kaeralill, Meelespea, Rukkilill, Pilvepai- Kaeralill<br><br><br><b>31.07- 04.08</b><br>I- Tuulepai, Vihmapai, Saialill, Võilill- Võilille rühmaruum<br><br>II- Tähepai, Sinilill, Mesimummid, Lepatriinud- Sinilille rühmaruum<br><br>III- Päikesetupsud, Mõmmikud, Krõllid, Sookurekesed, Naerupallid- Kaeralille rühmaruum<br><br>IV- Päikesepai, Päevalill, Vikerkaare, Kiilikesed- Päevalille rühmaruum<br><br>V- Rukkilill, Meelespea, Vikerkaarepai, Kaeralill- Rukkilille rühmaruum<br><br><br><b>07.08-11.08</b><br>I- Tuulepai, Vihmapai, Saialill, Võilill- Võilille rühmaruum<br><br>II- Tähepai, Sinilill, Mesimummid, Lepatriinud- Sinilille rühmaruum<br><br>III- Päikesetupsud, Mõmmikud, Krõllid, Sookurekesed, Naerupallid- Kaeralille rühmaruum<br><br>IV- Päikesepai, Päevalill, Vikerkaare, Kiilikesed- Päevalille rühmaruum<br><br>V- Rukkilill, Meelespea, Vikerkaarepai, Kaeralill- Rukkilille rühmaruum<br><br><br><b>14.08-18.08</b><br>I- Tuulepai, Vihmapai, Saialill- Saialille rühmaruum<br><br>II- Tähepai, Sinilill, Mesimummid, Lepatriinud- Sinilille rühmaruum<br><br>III- Päikesetupsud, Mõmmikud, Krõllid, Sookurekesed, Naerupallid- Kaeralille rühmaruum<br><br>IV- Päikesepai, Vikerkaare, Kiilikesed- Päevalille rühmaruum<br><br>V- Rukkilill, Meelespea, Vikerkaarepai, Kaeralill- Rukkilille rühmaruum<br><br>VI- Päevalill, Võilill- Võilille rühmaruum',
    createdAt: '09.05.2023',
  },
  {
    id: 2,
    title: 'Uute rühmade komplekteerimine eesootavaks õppeaastaks on alanud.',
    content:
      'Hea lapsevanem!<br>Ole hea veendu kas oled saanud lasteaiakoha avalduses märgitud e-postile kohapakkumise. Käesolevas teates on olemas ka rühmade nimekiri seisuga 20.03.2023. Nimekirjades on kajastatud vaid laste eesnimed ja perekonnanime esimene täht. Nimekiri leitav altpoolt, rühmadesse vastuvõtt algab 21 augustist 2023.a. Avatud uksed uutele lastele toimuvad mais 2023, täpsem info lasteaia sotsiaalmeedias (Facebook PAIde Lasteaed ning kodulehel www.pailasteaed.ee). Lisaküsimuste korral võtke kindlasti ühendust lasteaia direktoriga (5512 515 või direktor@pailasteaed.ee)',
    createdAt: '21.03.2023',
  },
];
